albasrah: 
  name: Al Basrah
  rules: 
    - 5
    - 6
    - 7

asadkhal: 
  name: Asad Khal
  rules: 
    - 1
    - 2
    - 3
    - 4

assaultongrozny:
  name: Assault on Grozny
  rules:
    - 1
    - 2
    - 3
    - 4
    - 7

assaultonmestia:
  name: Assault on Mestia
  rules:
    - 3
    - 4
    
bamyan:
  name: Bamyan
  rules:
    - 2
    - 3
    - 4
    - 7

battleofiadrang:
  name: Battle of Ia Drang
  rules: 
    - 1
    - 2
    - 3
    - 4
    - 9

beirut:
  name: Beirut
  rules:
    - 1
    - 2
    - 3
    - 4

bijarcanyons:
  name: Bijar Canyons
  rules:
    - 1
    - 2
    - 3
    - 4
    - 11

blackgold:
  name: Black Gold
  rules:
    - 1
    - 2
    - 3
    - 4
    - 7
    - 9
    - 10
    - 11

burningsands:
  name: Burning Sands
  rules:
    - 1
    - 3
    - 4

charliespoint:
  name: 'Charlie''s Point'
  rules: 
    - 3
    - 4

dovre:
  name: Dovre
  rules:
    - 1
    - 2
    - 3
    - 4

dovre_winter:
  name: Dovre (Winter)
  rules:
    - 1
    - 2
    - 3
    - 4

dragonfly:
  name: Dragon Fly
  rules:
    - 1
    - 3
    - 4
    - 5
    - 7
    - 9
    - 11
    
fallujahwest:
  name: Fallujah West
  rules:
    - 5
    - 7

foolsroad:
  name: Fools Road
  rules:
    - 1
    - 2
    - 3
    - 4
    - 9
    - 10
    - 11
    
gazabeach:
  name: Gaza Beach
  rules:
    - 1
    - 3
    - 4
    - 5
    - 7

hadespeak:
  name: Hades Peak
  rules: 
    - 2
    - 3
    - 4
    - 10
    - 11
    - 12

hill488:
  name: Hill 488
  rules:
    - 1
    - 3
    - 4

ironridge:
  name: Iron Ridge
  rules:
    - 1
    - 3
    - 5
    - 6
    - 7
    - 9

jabalalburj:
  name: Jabal Al Burj
  rules:
    - 1
    - 2
    - 3
    - 4

karbala:
  name: Karbala
  rules:
    - 5
    - 6
    - 7

kashandesert:
  name: Kashan Desert
  rules:
    - 1
    - 2
    - 3
    - 4
    - 11

khamisiyah:
  name: Khamisiyah
  rules:
    - 1
    - 2
    - 3
    - 4
    - 7
    - 9
    - 10
    - 11

kokan:
  name: Kokan
  rules:
    - 5
    - 6
    - 7

korengalvalley:
  name: Korengal Valley
  rules:
    - 3
    - 4
    - 5
    - 6
    - 7


kozelsk:
  name: Kozelsk
  rules:
    - 1
    - 2
    - 3
    - 4
    - 7

lashkarvalley:
  name: Lashkar Valley
  rules:
    - 5
    - 7

muttrahcity:
  name: Muttrah City
  rules:
    - 1
    - 2
    - 3
    - 4

nuijamaa:
  name: Nuijamaa
  rules:
    - 1
    - 2
    - 3
    - 4

operationarcher:
  name: Operation Archer
  rules:
    - 5
    - 6
    - 7

operationbarracuda:
  name: Operation Barracuda
  rules:
    - 2
    - 3
    - 4

operationghosttrain:
  name: Operation Ghost Train
  rules:
    - 1
    - 3
    - 4

operationmarlin:
  name: Operation Marlin
  rules:
    - 1
    - 2
    - 3
    - 4
    - 6
    - 7

operationsoulrebel:
  name: Operation Soul Rebel
  rules:
    - 1
    - 3
    - 4

pavlovskbay:
  name: Pavlovsk Bay
  rules:
    - 1
    - 2
    - 3
    - 4

qwairiver:
  name: Qwai River
  rules:
    - 1
    - 2
    - 3
    - 4

ramiel:
  name: Ramiel
  rules:
    - 3
    - 4
    - 5
    - 6
    - 7

saaremaa:
  name: Saaremaa
  rules:
    - 1
    - 2
    - 3
    - 4
    - 9
    - 10
    - 11

sbenehoutskirts:
  name: Sbeneh Outskirts
  rules:
    - 3
    - 4
    - 6
    - 7

shijiavalley:
  name: Shijia Valley
  rules:
    - 1
    - 2
    - 3
    - 4
    - 9
    - 11

silenteagle:
  name: Silent Eagle
  rules:
    - 1
    - 2
    - 3
    - 4
    - 11

tadsaeoffensive:
  name: Tad Sae Offensive
  rules:
    - 2
    - 3
    - 4
thefalklands:
  name: The Falklands
  rules:
    - 1
    - 2
    - 3
    - 4
    
ulyanovsk:
  name: Ulyanovsk
  rules:
    - 1
    - 2
    - 3
    - 4

vadsocity:
  name: Vadso City
  rules:
    - 1
    - 2
    - 3
    - 4
    - 9
    - 10
    - 11

wandashan:
  name: Wanda Shan
  rules:
    - 1
    - 2
    - 3
    - 4
    - 11
    
xiangshan:
  name: Xiangshan
  rules:
    - 2
    - 3
    - 4

yamalia:
  name: Yamalia
  rules:
    - 1
    - 2
    - 3
    - 4
    - 9
    - 11
